trial: 1
c_val: 1.0
hours: 24
expansion_threshold: 0.995
simulation_num: 3
flush_threshold: 1

use_lipinski_filter: False
#lipinski_filter_type: rule_of_5
use_radical_filter: False
use_hashimoto_filter: False
use_sascore_filter: False
#sa_threshold: 10.
use_ring_size_filter: False
#ring_size_threshold: 6
include_filter_result_in_reward: False

model_json: model/model_chembl220k.tf25.json
model_weight: model/model_chembl220k.tf25.best.ckpt.h5
output_dir: result/example01
reward_setting:
  reward_module: reward.Vina_reward
  reward_class: Vina_reward
policy_setting: 
  policy_module: policy.ucb1
  policy_class: Ucb1
token: model/tokens_chembl220k.pkl

vina_sf_name: vina
vina_cpus: 8
vina_receptor: data/1iep_receptor.pdbqt
vina_center: [15.190, 53.903, 16.917]
vina_box_size: [20, 20, 20]
vina_spacing: 0.375
vina_exhaustiveness: 32
vina_n_poses: 10
vina_base_score: -20
vina_min_rmsd: 1.0
vina_max_evals: 0
