c_val: 1.0
# threshold_type: [time, generation_num]
threshold_type: time
hours: 0.01
# generation_num: 100
expansion_threshold: 0.995
simulation_num: 3
flush_threshold: -1

#save and restart
save_checkpoint: True
restart: True
checkpoint_file: chemtsv2.ckpt.pkl

use_lipinski_filter: True
lipinski_filter:
  module: filter.lipinski_filter
  class: LipinskiFilter
  type: rule_of_5
#lipinski_filter_type: rule_of_5
use_radical_filter: True
radical_filter:
  module: filter.radical_filter
  class: RadicalFilter
use_hashimoto_filter: True
hashimoto_filter:
  module: filter.hashimoto_filter
  class: HashimotoFilter
use_sascore_filter: True
sascore_filter:
  module: filter.sascore_filter
  class: SascoreFilter
  threshold: 3.5
#sa_threshold: 10.
use_ring_size_filter: True
ring_size_filter:
  module: filter.ring_size_filter
  class: RingSizeFilter
  threshold: 6
use_pains_filter: False
pains_filter:
  module: filter.pains_filter
  class: PainsFilter
  type: [pains_a]
include_filter_result_in_reward: False

model_setting:
  model_json: model/model.tf25.json
  model_weight: model/model.tf25.best.ckpt.h5
output_dir: result/restart_example01
reward_setting: 
  reward_module: reward.logP_reward
  reward_class: LogP_reward
policy_setting: 
  policy_module: policy.ucb1
  policy_class: Ucb1
token: model/tokens.pkl
