trial: 1
c_val: 0.2
# threshold_type: [time, generation_num]
threshold_type: time
hours: 0.01
# generation_num: 100
expansion_threshold: 0.995
simulation_num: 3
flush_threshold: -1

use_lipinski_filter: False
#lipinski_filter_type: rule_of_5
use_radical_filter: True
use_hashimoto_filter: True
use_sascore_filter: True
#sa_threshold: 10.
use_ring_size_filter: False
#ring_size_threshold: 6
include_filter_result_in_reward: False

model_json: model/model.tf25.json
model_weight: model/model.tf25.best.ckpt.h5
output_dir: result/example01
reward_setting: 
  reward_module: reward.IPE_reward
  reward_class: IPE_reward
policy_setting: 
  policy_module: policy.ucb1
  policy_class: Ucb1
token: model/tokens.pkl

#parallelization strategy
leaf_parallel: False

#Gaussian setting
gau_functional: BLYP
gau_basis: STO-3G
gau_core_num: 40
gau_option: ipe
gau_solvent: 0
gau_error: 0
