trial: 1
c_val: 1.0
hours: 0.01
expansion_threshold: 0.995
simulation_num: 3

use_lipinski_filter: True
#lipinski_filter_type: rule_of_5
use_radical_filter: True
use_hashimoto_filter: True
use_sascore_filter: True
#sa_threshold: 3.5
use_ring_size_filter: True
#ring_size_threshold: 6

model_json: model/model.tf25.json
model_weight: model/model.tf25.best.ckpt.h5
output_dir: result/example01
reward_calculator: reward.dscore_reward

# Select "max_gauss" to activate, or "min_gauss" to deactivate.
scaling_function:
  EGFR: min_gauss
  BACE1: max_gauss
  ERBB2: min_gauss
  ABL: min_gauss
  SRC: min_gauss
  LCK: min_gauss
  PDGFRbeta: min_gauss
  VEGFR2: min_gauss
  FGFR1: min_gauss
  EPHB4: min_gauss
# Set the weight for each indicator.
weight:
  EGFR: 8
  BACE1: 5
  ERBB2: 1
  ABL: 1
  SRC: 1
  LCK: 1
  PDGFRbeta: 1
  VEGFR2: 1
  FGFR1: 1
  EPHB4: 1
  Solubility: 1
  Permeability: 1
  Toxicity: 1
  SAscore: 1
  QED: 1